services:
  erdmannfreunde.theme_toolbox.listener.disable_css_caching:
    class: ErdmannFreunde\ThemeToolboxBundle\EventListener\DisableCssCachingListener
    public: true

  erdmannfreunde.theme_toolbox.listener.bypass_mode_alert_message:
    class: ErdmannFreunde\ThemeToolboxBundle\EventListener\BypassModeAlertMessageListener
    arguments: ['@contao.framework']
    public: true
